#!/usr/bin/env bash
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Yadm bootstrap file

#: {{{ Variables

SYSTEM_TYPE=$(uname -s)  # Valid for UNIX / UNIX like systems

MACOS_VERSION=$(sw_vers -productVersion)  # gets macOS version number
MACOS_MOJAVE_BOOTS="$HOME/.config/yadm/macos/mojave_bootstrap"
MACOS_BIGSUR_BOOTS="$HOME/.config/yadm/macos/bigsur_bootstrap"

#: }}}

#: {{{ Functions

# Confirm bootstraping action
# Accepts bootstrap file location as function argument
ask_confirmation() {

  # Defining local parameter for argument
  local boostrap_file=$1

  while true; do
      read -p "Do you wish to run bootstrap files? (y/n): " yn
      case $yn in
  	[Yy]* ) bash $boostrap_file; break;;
  	[Nn]* ) echo "Aborting..."; break;;
  	* ) echo "Please answer yes or no.";;
      esac
  done

}

#: }}}

# If system type is Darwin (macOS)
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  echo "Detected system type: $SYSTEM_TYPE"
  echo "Detected macOS version: $MACOS_VERSION" 

  # If version name contains 14
  if [[ "$MACOS_VERSION" == *"14"* ]]; then
    echo -e "System name: macOS Mojave\n"
    # Boostrapping macOS Mojave
    ask_confirmation $MACOS_MOJAVE_BOOTS

  else
    echo "There aren't any bootstrap files for this macOS version"
  fi
fi
