#!/usr/bin/env sh
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Yabai configuration file
# For starting yabai as a service use
# $ brew services start yabai
# For reloading config file use:
# $ brew services restart yabai
# Keybindings are defined using skhd

#: Tiling options {{{ 

#: Layout (managed, bsp, float) {{{
# Supported: managed, bsp (binary space partion)
# or float

# General layout
yabai -m config layout bsp

# Override default layout for space 2 only
#yabai -m config --space 10 layout float

#: }}}

#: Windows spawning {{{

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

#: }}}

#: Padding and gaps {{{

# Set all padding and gaps (default: 0)
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0

# Override gaps for space 2 only
#yabai -m config --space 2 window_gap 0

#: }}}

#: Split ratios {{{

# Auto balance makes it so all windows always occupy the same space, independent of how deeply nested they are in the window tree.
# When a new window is inserted or a window is removed, the split ratios will be automatically adjusted.

# auto balance on or off (default: off)

yabai -m config auto_balance off

# If auto balance is disabled, the split ratio defines how much space each window occupies after a new split is created.
# A value of 0.5 means that both old and new window occupy the same space; a value of 0.2 means that the old window occupies 20% of the available space and the new window occupies 80% of the available space.
# New windows are inserted at the right or bottom side. The ratio needs to be between 0 and 1.

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5

# :}}}

# :}}}

#: Mouse support {{{

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus off
#: }}}

#: Window modifications {{{

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
# show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# render all unfocused windows with x% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

#: }}}

#: Status bar {{{

# add 20 padding to the top and bottom of all spaces
# regardless of the display it belongs to
# Displaying gap
# For using with Übersicht status bar app

#yabai -m config external_bar all:28:0

#: }}}

#: Specific apps config {{{

# System Preferences
# Always float the whole app
yabai -m rule --add app="^System Preferences$" manage=off

# Flux
# Always float the whole app
yabai -m rule --add app="^Flux$" manage=off

# VeraCrypt
# Always float the whole app
yabai -m rule --add app="^VeraCrypt$" manage=off

# Firefox
# Always float dialog boxes
yabai -m rule --add app="^Firefox$" title="^Opening .*$" manage=off

# JetBrains
# Always float PyCharm welcome window
yabai -m rule --add app="^PyCharm$" title="Welcome to PyCharm" manage=off
# Always float WebStorm welcome window
yabai -m rule --add app="^WebStorm$" title="Welcome to WebStorm" manage=off

# Calculator
yabai -m rule --add app="^Calculator$" manage=off

# Finder
# NOT WORKING
# Always float dialgo boxes
# yabai -m rule --add app="^Finder$" title="^Opening .*$" manage=off
#: }}}

echo "yabai configuration loaded.."
