#!/usr/bin/env bash
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# ANSI color escape codes:
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'  # No color

# Homebrew
brewfile="$HOME/.config/brew/Brewfile"

# Success message
success_msg="${GREEN} Success! ${NC}"
regenbrewfile_msg="${YELLOW}Regenerating Brewfile...${NC}"

echo -e $regenbrewfile_msg
# Force option used to overwrite Brewfile if it
# already exists.
# TODO make `yadm add` fail if brew dump fails
brew bundle dump --file=$brewfile --force
echo -e $success_msg

# Add brewfile to Yadm repo
# TODO check if file was added to yadm repo
echo -e "${YELLOW} Adding Brewfile to yadm repository..."
yadm add $brewfile
echo -e $success_msg
