#!/usr/bin/env bash

# Commands here are working, unless stated otherwise.
# Based on ~/.macos — http://mths.be/macos
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit' #working on Big Sur

# TODO: test sudo command. Ask for the administrator password upfront
sudo -v

###############################################################################
# General UI/UX                                                               #
###############################################################################

# TODO: find command that disable the sound effects on boot
# for macos Mojave none of the commands bellow works:
#sudo nvram SystemAudioVolume=" " does not work
#sudo nvram SystemAudioVolume=%80 does not work
#sudo nvram SystemAudioVolume=%00 does not work
#sudo nvram SystemAudioVolume=%01 does not work

# for Big Sur you can change this option on the UI

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true  # working on Big Sur
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true  # working on Big Sur

# Hide files and icons from Desktop
defaults write com.apple.finder CreateDesktop false  # working on Big Sur
killall Finder
###############################################################################
# Keyboard                                                                    #
###############################################################################

# Blazingly fast key repeat os macos, very useful for vim, needs reboot
# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1  # working on Bigsur
defaults write NSGlobalDomain InitialKeyRepeat -int 10  #working on Big Sur
# Alternatively, for a slight slower value you can use 
#defaults write NSGlobalDomain InitialKeyRepeat -int 15
