#!/usr/bin/env bash

# Commands here are working, unless stated otherwise.
# Based on ~/.macos — http://mths.be/macos
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit' #working on Big Sur

# TODO test sudo command. Ask for the administrator password upfront
sudo -v

###############################################################################
# General UI/UX                                                               #
###############################################################################

# TODO find command that disable the sound effects on boot
# for macos Mojave none of the commands bellow works:
# for Big Sur you can change this option on the UI

#sudo nvram SystemAudioVolume=" " does not work
#sudo nvram SystemAudioVolume=%80 does not work
#sudo nvram SystemAudioVolume=%00 does not work
#sudo nvram SystemAudioVolume=%01 does not work

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Hide files and icons from Desktop
defaults write com.apple.finder CreateDesktop false  # working on Big Sur
killall Finder
###############################################################################
# Keyboard                                                                    #
###############################################################################

# Blazingly fast key repeat os macos, very useful for vim, needs reboot
# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1  # working on Bigsur
defaults write NSGlobalDomain InitialKeyRepeat -int 10  #working on Big Sur
# Alternatively, for a slight slower value you can use 
#defaults write NSGlobalDomain InitialKeyRepeat -int 15

###############################################################################
# Apps                                                                        #
###############################################################################

# iTerm
# Make sure iTerm is closed
osascript -e 'tell application "iTerm" to quit'
# Make sure there are not cached iTerm preferences at ~/Library/Preferences

# Double check
iterm_cached_prefs=$(ls | grep com.googlecode.iterm)
for item in iterm_cached_prefs
do
  echo $item
end

# Copy preferences from $HOME/.config/macos/symlinked/iterm2

